USE [master]
GO
/****** Object:  Database [db_searchEngine]    Script Date: 26/03/2024 21:33:47 ******/
CREATE DATABASE [db_searchEngine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_searchEngine', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\db_searchEngine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_searchEngine_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\db_searchEngine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [db_searchEngine] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_searchEngine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db_searchEngine] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_searchEngine] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_searchEngine] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_searchEngine] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_searchEngine] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_searchEngine] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db_searchEngine] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_searchEngine] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_searchEngine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_searchEngine] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_searchEngine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_searchEngine] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_searchEngine] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_searchEngine] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_searchEngine] SET  DISABLE_BROKER 
GO
ALTER DATABASE [db_searchEngine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_searchEngine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_searchEngine] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_searchEngine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_searchEngine] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_searchEngine] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db_searchEngine] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db_searchEngine] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [db_searchEngine] SET  MULTI_USER 
GO
ALTER DATABASE [db_searchEngine] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_searchEngine] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db_searchEngine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db_searchEngine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_searchEngine] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db_searchEngine] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [db_searchEngine] SET QUERY_STORE = ON
GO
ALTER DATABASE [db_searchEngine] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [db_searchEngine]
GO
/****** Object:  Table [dbo].[Histories]    Script Date: 26/03/2024 21:33:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Histories](
	[HistoryId] [int] IDENTITY(1,1) NOT NULL,
	[Keyword] [nvarchar](500) NOT NULL,
	[Url] [nvarchar](1000) NOT NULL,
	[Position] [nvarchar](500) NOT NULL,
	[SearchTime] [datetime] NOT NULL,
	[SearchEngine] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Histories] PRIMARY KEY CLUSTERED 
(
	[HistoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [db_searchEngine] SET  READ_WRITE 
GO
